import type { Ticket } from "./types";

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "4521",
    title: "Payment failed for airport transfer",
    status: "Open",
    ticketType: "report_issue",
    linkedTripId: "TR-98214",
    role: "Passenger",
    category: "Payment",
    time: "5 min ago",
    user: {
      name: "Sarah Lee",
      role: "Passenger",
      memberSince: "2023",
      email: "sarah.lee@example.com",
      phone: "+213 555 01 23 45",
    },
    trip: {
      tripId: "TR-98214",
      date: "12 Apr 2026 · 08:30",
      route: "City Centre → Airport",
      price: "2 400 DA",
      status: "Payment failed",
    },
    payment: { method: "CIB Card", transactionStatus: "Declined" },
    notes: [
      {
        id: "n1",
        adminName: "Aymen B.",
        timestamp: "Apr 12, 08:42",
        content: "Card declined twice. Possible insufficient funds or 3DS failure. Asked user to try another method.",
      },
      {
        id: "n2",
        adminName: "Rania K.",
        timestamp: "Apr 12, 09:05",
        content: "Escalate to billing team if user can't resolve within 2 hours.",
      },
    ],
    messages: [
      { id: "m1", sender: "Sarah Lee", senderType: "user", content: "Hi, my payment just failed and the app shows an error. The trip was supposed to be today!", timestamp: "08:31" },
      { id: "m2", sender: "Admin", senderType: "admin", content: "Hello Sarah, I'm looking into this right now. Can you confirm which card you used?", timestamp: "08:35" },
      { id: "m3", sender: "Sarah Lee", senderType: "user", content: "I used my CIB Visa card ending in 4422.", timestamp: "08:37" },
      { id: "m4", sender: "Admin", senderType: "admin", content: "Thank you. Our system shows the transaction was declined by your bank. Please try a different payment method or contact your bank.", timestamp: "08:40" },
    ],
    activity: [
      { id: "a1", type: "created", description: "Ticket created by Sarah Lee", timestamp: "Apr 12, 08:31" },
      { id: "a2", type: "status_change", description: "Status set to Open", timestamp: "Apr 12, 08:31", actor: "System" },
      { id: "a3", type: "admin_reply", description: "Admin replied to user", timestamp: "Apr 12, 08:35", actor: "Admin" },
      { id: "a4", type: "admin_reply", description: "Admin replied again with bank advice", timestamp: "Apr 12, 08:40", actor: "Admin" },
    ],
  },
  {
    id: "4518",
    title: "Driver did not arrive at pickup location",
    status: "In Progress",
    ticketType: "report_issue",
    linkedTripId: "TR-97890",
    role: "Passenger",
    category: "Ride",
    time: "22 min ago",
    user: {
      name: "Yacine M.",
      role: "Passenger",
      memberSince: "2022",
      email: "yacine.m@gmail.com",
      phone: "+213 555 98 76 54",
    },
    trip: {
      tripId: "TR-97890",
      date: "12 Apr 2026 · 07:00",
      route: "Bab Ezzouar → Les Pins",
      price: "950 DA",
      status: "Cancelled by driver",
    },
    payment: { method: "Cash", transactionStatus: "Not charged" },
    notes: [
      {
        id: "n1",
        adminName: "Aymen B.",
        timestamp: "Apr 12, 07:25",
        content: "Driver reportedly had a vehicle breakdown. Verified via driver logs. Issuing a free ride coupon.",
      },
      {
        id: "n2",
        adminName: "Aymen B.",
        timestamp: "Apr 12, 07:40",
        content: "Coupon code MVR-FREE-2026 generated and sent to user email.",
      },
    ],
    messages: [
      { id: "m1", sender: "Yacine M.", senderType: "user", content: "My driver never showed up and cancelled the ride 5 minutes after I waited.", timestamp: "07:18" },
      { id: "m2", sender: "Admin", senderType: "admin", content: "Hi Yacine, I'm sorry for the inconvenience. I'm checking what happened with your driver.", timestamp: "07:22" },
      { id: "m3", sender: "Yacine M.", senderType: "user", content: "I was late to work because of this!", timestamp: "07:23" },
      { id: "m4", sender: "Admin", senderType: "admin", content: "I completely understand. The driver had a technical issue. I'm sending you a free ride coupon as compensation.", timestamp: "07:28" },
      { id: "m5", sender: "Yacine M.", senderType: "user", content: "Okay, thank you. I'll check my email.", timestamp: "07:30" },
    ],
    activity: [
      { id: "a1", type: "created", description: "Ticket created by Yacine M.", timestamp: "Apr 12, 07:18" },
      { id: "a2", type: "status_change", description: "Status changed to In Progress", timestamp: "Apr 12, 07:22", actor: "Aymen B." },
      { id: "a3", type: "admin_reply", description: "Admin replied and investigated", timestamp: "Apr 12, 07:22", actor: "Aymen B." },
      { id: "a4", type: "admin_reply", description: "Compensation coupon sent to user", timestamp: "Apr 12, 07:28", actor: "Aymen B." },
    ],
  },
  {
    id: "4512",
    title: "Account suspended without reason",
    status: "Pending",
    ticketType: "submit_ticket",
    role: "Driver",
    category: "Account",
    time: "1h ago",
    user: {
      name: "Karim D.",
      role: "Driver",
      memberSince: "2021",
      email: "karim.driver@moviroo.dz",
      phone: "+213 555 44 33 22",
    },
    trip: {
      tripId: "—",
      date: "—",
      route: "—",
      price: "—",
      status: "Account suspended",
    },
    payment: { method: "Bank transfer", transactionStatus: "Pending review" },
    notes: [
      {
        id: "n1",
        adminName: "Rania K.",
        timestamp: "Apr 12, 07:05",
        content: "Account was flagged by fraud detection for 3 consecutive cancellations. Need driver to confirm reason.",
      },
      {
        id: "n2",
        adminName: "Rania K.",
        timestamp: "Apr 12, 07:15",
        content: "Waiting for driver's response before lifting suspension. Do not reactivate without manager approval.",
      },
      {
        id: "n3",
        adminName: "Aymen B.",
        timestamp: "Apr 12, 07:50",
        content: "Manager notified. Will review cancellation logs today.",
      },
    ],
    messages: [
      { id: "m1", sender: "Karim D.", senderType: "user", content: "My account is suspended and I don't know why. I have rides to do today!", timestamp: "07:02" },
      { id: "m2", sender: "Admin", senderType: "admin", content: "Hello Karim, your account was flagged for multiple ride cancellations. Can you explain what happened?", timestamp: "07:08" },
      { id: "m3", sender: "Karim D.", senderType: "user", content: "The passengers were at wrong locations, so I had to cancel. It wasn't my fault.", timestamp: "07:12" },
      { id: "m4", sender: "Admin", senderType: "admin", content: "Understood. We are reviewing your ride logs. Please wait while we complete the investigation.", timestamp: "07:18" },
    ],
    activity: [
      { id: "a1", type: "created", description: "Ticket created by Karim D.", timestamp: "Apr 12, 07:02" },
      { id: "a2", type: "status_change", description: "Status changed to Pending", timestamp: "Apr 12, 07:08", actor: "Rania K." },
      { id: "a3", type: "admin_reply", description: "Admin requested driver explanation", timestamp: "Apr 12, 07:08", actor: "Rania K." },
      { id: "a4", type: "status_change", description: "Awaiting manager review", timestamp: "Apr 12, 07:50", actor: "Aymen B." },
    ],
  },
  {
    id: "4505",
    title: "App crashes when starting a new ride",
    status: "In Progress",
    ticketType: "report_issue",
    linkedTripId: "TR-97112",
    role: "Driver",
    category: "Technical",
    time: "2h ago",
    user: {
      name: "Nadia R.",
      role: "Driver",
      memberSince: "2023",
      email: "nadia.r@moviroo.dz",
      phone: "+213 555 77 88 99",
    },
    trip: {
      tripId: "TR-97112",
      date: "12 Apr 2026 · 06:15",
      route: "Hussein Dey → Dar El Beïda",
      price: "800 DA",
      status: "Interrupted",
    },
    payment: { method: "Moviroo Wallet", transactionStatus: "Refunded" },
    notes: [
      {
        id: "n1",
        adminName: "Aymen B.",
        timestamp: "Apr 12, 06:30",
        content: "Driver is on Android 11, app version 3.2.1. Known crash bug with 'start ride' button. Forwarded to tech team.",
      },
    ],
    messages: [
      { id: "m1", sender: "Nadia R.", senderType: "user", content: "Every time I press 'Start Ride' the app crashes immediately. I already lost one ride.", timestamp: "06:20" },
      { id: "m2", sender: "Admin", senderType: "admin", content: "Hi Nadia, sorry about that. Which phone and app version are you using?", timestamp: "06:25" },
      { id: "m3", sender: "Nadia R.", senderType: "user", content: "Samsung Galaxy A52, app version 3.2.1.", timestamp: "06:27" },
      { id: "m4", sender: "Admin", senderType: "admin", content: "Thank you. This is a known issue we are fixing. Please try clearing app cache and restart. A patch is coming in 24h.", timestamp: "06:32" },
    ],
    activity: [
      { id: "a1", type: "created", description: "Ticket created by Nadia R.", timestamp: "Apr 12, 06:20" },
      { id: "a2", type: "status_change", description: "Status changed to In Progress", timestamp: "Apr 12, 06:25", actor: "Aymen B." },
      { id: "a3", type: "admin_reply", description: "Bug reported to tech team", timestamp: "Apr 12, 06:30", actor: "Aymen B." },
      { id: "a4", type: "escalated", description: "Issue escalated to engineering", timestamp: "Apr 12, 06:35", actor: "Aymen B." },
    ],
  },
  {
    id: "4498",
    title: "Incorrect fare charged — different from estimate",
    status: "Resolved",
    ticketType: "report_issue",
    linkedTripId: "TR-96980",
    role: "Passenger",
    category: "Payment",
    time: "3h ago",
    user: {
      name: "Amira B.",
      role: "Passenger",
      memberSince: "2022",
      email: "amira.b@yahoo.fr",
      phone: "+213 555 12 34 56",
    },
    trip: {
      tripId: "TR-96980",
      date: "11 Apr 2026 · 19:45",
      route: "Alger Centre → Hydra",
      price: "1 850 DA",
      status: "Completed",
    },
    payment: { method: "Dahabia Card", transactionStatus: "Charged — partial refund issued" },
    notes: [
      {
        id: "n1",
        adminName: "Rania K.",
        timestamp: "Apr 11, 20:10",
        content: "Surge pricing was active during the ride. Difference of 350 DA refunded as wallet credit.",
      },
    ],
    messages: [
      { id: "m1", sender: "Amira B.", senderType: "user", content: "The app estimated 1500 DA but I was charged 1850 DA. Why?", timestamp: "20:05" },
      { id: "m2", sender: "Admin", senderType: "admin", content: "Hello Amira, surge pricing was active in your area last night. I've issued a 350 DA credit to your wallet.", timestamp: "20:12" },
      { id: "m3", sender: "Amira B.", senderType: "user", content: "Okay, I can see the credit. Thank you!", timestamp: "20:15" },
    ],
    activity: [
      { id: "a1", type: "created", description: "Ticket created by Amira B.", timestamp: "Apr 11, 20:05" },
      { id: "a2", type: "status_change", description: "Status changed to In Progress", timestamp: "Apr 11, 20:08", actor: "Rania K." },
      { id: "a3", type: "admin_reply", description: "Partial refund issued as wallet credit", timestamp: "Apr 11, 20:12", actor: "Rania K." },
      { id: "a4", type: "resolved", description: "Ticket resolved — user confirmed credit received", timestamp: "Apr 11, 20:16", actor: "Rania K." },
    ],
  },
  {
    id: "4491",
    title: "Can't update profile phone number",
    status: "Resolved",
    ticketType: "submit_ticket",
    role: "Driver",
    category: "Account",
    time: "5h ago",
    user: {
      name: "Omar Z.",
      role: "Driver",
      memberSince: "2020",
      email: "omar.z@moviroo.dz",
      phone: "+213 555 65 43 21",
    },
    trip: { tripId: "—", date: "—", route: "—", price: "—", status: "N/A" },
    payment: { method: "N/A", transactionStatus: "N/A" },
    notes: [
      {
        id: "n1",
        adminName: "Aymen B.",
        timestamp: "Apr 12, 03:10",
        content: "OTP validation was failing due to a carrier issue. Manually updated the phone number after identity verification.",
      },
    ],
    messages: [
      { id: "m1", sender: "Omar Z.", senderType: "user", content: "I've been trying to change my phone number for 2 days. The OTP never arrives.", timestamp: "03:05" },
      { id: "m2", sender: "Admin", senderType: "admin", content: "Hi Omar, this is a known carrier issue. I can verify your identity and update it manually.", timestamp: "03:08" },
      { id: "m3", sender: "Omar Z.", senderType: "user", content: "Great, what do you need from me?", timestamp: "03:09" },
      { id: "m4", sender: "Admin", senderType: "admin", content: "Please confirm your national ID number and old phone number. Done — your number has been updated.", timestamp: "03:12" },
      { id: "m5", sender: "Omar Z.", senderType: "user", content: "Perfect, it works now. Thank you!", timestamp: "03:15" },
    ],
    activity: [
      { id: "a1", type: "created", description: "Ticket created by Omar Z.", timestamp: "Apr 12, 03:05" },
      { id: "a2", type: "status_change", description: "Status changed to In Progress", timestamp: "Apr 12, 03:08", actor: "Aymen B." },
      { id: "a3", type: "admin_reply", description: "Identity verified, number updated manually", timestamp: "Apr 12, 03:12", actor: "Aymen B." },
      { id: "a4", type: "resolved", description: "Ticket resolved — driver confirmed fix", timestamp: "Apr 12, 03:16", actor: "Aymen B." },
    ],
  },
  {
    id: "4488",
    title: "Cannot log in – forgot password",
    status: "Open",
    ticketType: "submit_ticket",
    role: "Passenger",
    category: "Account",
    time: "30 min ago",
    user: { name: "Lina K.", role: "Passenger", memberSince: "2024", email: "lina.k@example.com", phone: "+213 555 00 11 22" },
    trip: { tripId: "—", date: "—", route: "—", price: "—", status: "N/A" },
    payment: { method: "N/A", transactionStatus: "N/A" },
    notes: [],
    messages: [
      { id: "m1", sender: "Lina K.", senderType: "user", content: "I forgot my password and the reset email never arrives.", timestamp: "09:10" },
    ],
    activity: [
      { id: "a1", type: "created", description: "Ticket created by Lina K.", timestamp: "Apr 8, 09:10" },
    ],
  },
  {
    id: "4530",
    title: "Driver took wrong route and overcharged",
    status: "Open",
    ticketType: "report_issue",
    linkedTripId: "TR-99001",
    role: "Passenger",
    category: "Ride",
    time: "10 min ago",
    user: { name: "Mehdi A.", role: "Passenger", memberSince: "2023", email: "mehdi.a@moviroo.dz", phone: "+213 555 55 66 77" },
    trip: { tripId: "TR-99001", date: "8 Apr 2026 · 10:05", route: "Kouba → Bir Mourad Raïs", price: "1 200 DA", status: "Completed" },
    payment: { method: "Moviroo Wallet", transactionStatus: "Charged" },
    notes: [],
    messages: [
      { id: "m1", sender: "Mehdi A.", senderType: "user", content: "The driver went through Hydra instead of the direct route. I was charged 1 200 DA but the estimate was 900 DA.", timestamp: "10:08" },
    ],
    activity: [
      { id: "a1", type: "created", description: "Ticket created by Mehdi A.", timestamp: "Apr 8, 10:08" },
    ],
  },
];